language: node_js
node_js:
- 12.10.0
sudo: required
addons:
  chrome: stable
  ssh_known_hosts: 51.178.82.205
branches:
  only:
  - master
before_deploy:
- openssl aes-256-cbc -K $encrypted_a492e0f2af60_key -iv $encrypted_a492e0f2af60_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
before_install:
 - npm install -g @angular/cli
 - npm install
 - npm update
script:
 - echo "npm test temporarily disabled"
install:
- docker network create officemanager-back_office-manager-bridge
- docker-compose up -d --build
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/ root@51.178.82.205:/deploy/officemanager-front
  on:
    branch: master
after_deploy:
- ssh root@51.178.82.205 'chmod 777 /deploy/officemanager-front/script.sh'
- ssh root@51.178.82.205 '/deploy/officemanager-front/script.sh'
after_success:
- wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- "./send.sh success $WEBHOOK_URL"
after_failure:
- wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- "./send.sh failure $WEBHOOK_URL"
