language: node_js
node_js:
- 12.10.0
sudo: required
addons:
  chrome: stable
  ssh_known_hosts: 92.222.9.74
branches:
  only:
  - master
before_deploy:
- openssl aes-256-cbc -K $encrypted_a492e0f2af60_key -iv $encrypted_a492e0f2af60_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
install:
- yarn install
script:
- echo "yarn test temporarily disabled"
- yarn run build:prod
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/ root@92.222.9.74:/deploy/officemanager-front
  on:
    branch: master
after_deploy:
- ssh root@92.222.9.74 'chmod 777 /deploy/officemanager-front/script.sh'
- ssh root@92.222.9.74 '/deploy/officemanager-front/script.sh'
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
