language: node_js
node_js:
- 12.10.0
sudo: required
addons:
  chrome: stable
  ssh_known_hosts: 92.222.9.74
branches:
  only:
  - dev
before_deploy:
- openssl aes-256-cbc -K $encrypted_7c3617b6e37f_key -iv $encrypted_7c3617b6e37f_iv -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
install:
- yarn install
script:
- echo "yarn test temporarily disabled"
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/ root@92.222.9.74:/deploy/officemanager-front
  on:
    branch: dev
after_deploy:
- ssh root@92.222.9.74 'chmod 777 /deploy/officemanager-front/script.sh'
- ssh root@92.222.9.74 '/deploy/officemanager-front/script.sh'


