version: '3.7'

services:

  angular:
    container_name: office_managaer_front
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '50000:4200'
