version: '3.7'

services:

  example:
    container_name: office_manager_front
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '50000:50000'
    networks: 
      default:
        external: 
          name: office-manager-bridge